spring:
  application:
    name: wallet-microservice
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./database/leovegas
    driverClassName: org.h2.Driver
    username: leovegas
    password: leovegas
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      show-sql: true

server:
  port: 8080
